<?xml version="1.0"?>
<package format="3">
  <name>seyond_mapping</name>
  <version>0.1.0</version>
  <description>Seyond inno-lidar-sdk ROS 2 driver and KISS-ICP map accumulator.</description>
  <maintainer email="187580000+armutie@users.noreply.github.com">armutie</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>boost</depend>

  <exec_depend>kiss_icp</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
